# Generated by Django 5.2.6 on 2025-12-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
    ]
